server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/products/{*segment}
              filters: 
                - RewritePath=/api/products/?(?<segment>.*), /products/$\{segment}
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - RewritePath=/api/users/(?<segment>.*), /users/$\{segment}
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/api/inventories/**
              filters:
                - RewritePath=/api/inventories/(?<segment>.*), /inventories/$\{segment}  
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**
              filters:
                - RewritePath=/api/orders/(?<segment>.*), /orders/$\{segment}
            - id: cart-service
              uri: lb://cart-service
              predicates:
                - Path=/api/carts/**
              filters:
                - RewritePath=/api/carts/(?<segment>.*), /carts/$\{segment}
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/payments/**
              filters:
                - RewritePath=/api/payments/(?<segment>.*), /payments/$\{segment}
security:
  role-rules:
    '[GET:/api/products/**]': ["ADMIN", "USER"]
    '[POST:/api/products/**]': ["ADMIN"]
    '[PUT:/api/products/**]': ["ADMIN"]
    '[DELETE:/api/products/**]': ["ADMIN"]

