eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/ecommerce_users}
